# Generated by Django 3.1.5 on 2021-02-24 21:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210221_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name=ckeditor.fields.RichTextField(blank=True, null=True)),
        ),
    ]
